experiment: scphere_mvae
output_dir: /home/romainlhardy/code/hyperbolic-cancer/models/mvae

optimizer:
  class: Adam
  options:
    lr: 1.0e-3
    betas: [0.9, 0.999]
    weight_decay: 0.0
    eps: 1.0e-8

scheduler:
  class: OneCycleLR
  options:
    epochs: 250
    pct_start: 0.1

data:
  options:
    mtx_path: /home/romainlhardy/code/hyperbolic-cancer/data/scphere/uc_epi.mtx
    batch_paths:
      - /home/romainlhardy/code/hyperbolic-cancer/data/scphere/uc_epi_batch_patient.tsv
      - /home/romainlhardy/code/hyperbolic-cancer/data/scphere/uc_epi_batch_health.tsv
      - /home/romainlhardy/code/hyperbolic-cancer/data/scphere/uc_epi_batch_location.tsv
  batch_size: 256
  num_workers: 16

lightning:
  model:
    components: e10,h10,s10
    fixed_curvature: true
    options:
      encoder_layer: [256, 128]
      decoder_layer: [128, 256]
      batch_invariant: false
      observation_dist: "nb"
      scalar_parametrization: true

trainer:
  max_epochs: 250
  log_every_n_steps: 50
  enable_progress_bar: false
  precision: 32
  accelerator: gpu
  devices: 2
  strategy: ddp_find_unused_parameters_true