experiment: lung_mvae_e20h20s20
output_dir: /home/romainlhardy/code/hyperbolic-cancer/models/mvae

optimizer:
  class: Adam
  options:
    lr: 1.0e-3
    betas: [0.9, 0.999]
    weight_decay: 1.0e-5
    eps: 0.01

scheduler:
  class: OneCycleLR
  options:
    epochs: 1000
    pct_start: 0.1

data:
  options:
    mtx_path: /home/romainlhardy/code/hyperbolic-cancer/data/lung/Exp_data_UMIcounts.mtx
    batch_paths:
      - /home/romainlhardy/code/hyperbolic-cancer/data/lung/batch.tsv
    preprocessing_options:
      normalize: true
      log1p: true
      top_genes: 2000
      scale: true
  batch_size: 256
  num_workers: 8

lightning:
  model:
    components: e20,h20,s20
    fixed_curvature: true
    options:
      encoder_layer: [256, 128, 64]
      decoder_layer: [64, 128, 256]
      batch_invariant: true
      observation_dist: nb
      scalar_parametrization: true
      beta: 1.0

trainer:
  max_epochs: 1000
  log_every_n_steps: 50
  enable_progress_bar: false
  precision: 32
  accelerator: gpu
  devices: 2
  strategy: ddp_find_unused_parameters_false