experiment: lung_umap2
output_dir: /home/romainlhardy/code/hyperbolic-cancer/models/umap

data:
  mtx_path: /home/romainlhardy/code/hyperbolic-cancer/data/lung/Exp_data_UMIcounts.mtx
  batch_paths:
    - /home/romainlhardy/code/hyperbolic-cancer/data/lung/batch.tsv

model:
  preprocess:
    normalize: true
    log1p: true
    top_genes: 2000
    scale: true
  pca:
    n_comps: 50
  harmony:
    theta: 2.0
    max_iter_harmony: 15
  neighbors:
    n_neighbors: 15
    metric: euclidean
  umap:
    n_components: 2