experiment: cellxgene_tsne2
output_dir: /home/romainlhardy/code/hyperbolic-cancer/models/tsne

data:
  mtx_path: /home/romainlhardy/code/hyperbolic-cancer/data/cellxgene/cellxgene_sample_counts.mtx
  batch_paths:
    - /home/romainlhardy/code/hyperbolic-cancer/data/cellxgene/cellxgene_sample_batch.tsv

model:
  preprocess:
    normalize: false
    log1p: true
    top_genes: null
    scale: true
  pca:
    n_comps: 50
  harmony:
    theta: 2.0
    max_iter_harmony: 15
  neighbors:
    n_neighbors: 15
    metric: euclidean
  tsne:
    perplexity: 30
    learning_rate: 1000
    random_state: 32
    n_jobs: -1
